### PR TITLE
Bump hub version to 0.11

### LINKED ISSUE #82: Upgrade to z2jh 0.11
We're currently on z2jh 0.9. There are a lot of improvements, security & otherwise, in v0.11 - we should upgrade.

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Closes https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/82

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
I'm getting the following error when trying to deploy this to staging :(
```
Error: UPGRADE FAILED: cannot patch "hub-db-dir" with kind PersistentVolumeClaim: PersistentVolumeClaim "hub-db-dir" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims
```

@consideratio or @yuvipanda, do you know what might be going on?

**Comment by yuvipanda** [comment]
@GeorgianaElena oh, hmm - interesting! This looks like it's trying to change the size of the hub-db PVC, not sure why. Can you check what the current size is and see what we're asking it to be?

**Comment by GeorgianaElena** [comment]
It looks like the current size is 1Gi for the staging hub and 10Gi for the prod one.

The prod one has its size configured [here](https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/staging/deployments/utoronto/config/prod.yaml#L6), but the staging one [doesn't](https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/staging/deployments/utoronto/config/staging.yaml), or at least I don't find it. Maybe the default size has changed and we should be explicit that we still want the 1Gi? 

Update: Being explicit about its size, doesn't do any difference :(

**Comment by GeorgianaElena** [comment]
Thanks to a recent discussion on Gitter, I managed to get the deployment to pass by specifying the `storageClassName` :heart: 
wieee :heart:

**Comment by yuvipanda** [comment]
@GeorgianaElena awesome! Let's wait until Toronto is asleep before we deploy to prod? Feel free to test on staging though :)

**Comment by jsg-uoft** [comment]
@GeorgianaElena if you can let me know when you want to push the change (as well as duration although I imagine it's more or less instant) I can put up a service notice. Just good to have in case there are any night owls interacting with the system at the same time.

**Comment by yuvipanda** [comment]
@jsg-uoft makes sense! It's pretty instant, but it's big enough that a service notice seems appropriate. Where would it be made visible?

**Comment by jsg-uoft** [comment]
@yuvipanda we'd post it to https://www.systemstatus.utoronto.ca/ and then advertise the link to the community for awareness. It may introduce a good conversation about feature changes (if any) as well!

**Comment by GeorgianaElena** [comment]
@jsg-uoft I was thinking about pushing the change at around 4am Toronto time. I could set and alarm if this needs to be precise.

@yuvipanda, the error I got before, was actually because of me messing with the config. I have now fixed it.

**Comment by yuvipanda** [comment]
> @yuvipanda we'd post it to [systemstatus.utoronto.ca](https://www.systemstatus.utoronto.ca/) and then advertise the link to the community for awareness. It may introduce a good conversation about feature changes (if any) as well!

Makes sense! This shouldn't have any user facing changes I think. Thanks for being on top of it!

**Comment by jsg-uoft** [comment]
Thanks @GeorgianaElena I will post an announcement then for 4:00 a.m. Thurs. Feb. 18th (Eastern) and put a pointer to it into Teams. I'll just provide the bare bones info, so if you or @yuvipanda can monitor for questions that would be great!

**Comment by yuvipanda** [comment]
@jsg-uoft awesome. Just make sure it says we don't expect disruption nor new features :)

**Review by consideRatio — APPROVED** [review]
This LGTM!

Note on the imagePullSecret section, create and enabled are both set but you should only need one as they are aliases. But, due to a bug in 0.11.1 you should use `.create` rather than `.enabled` if one is chosen.

**Comment by jsg-uoft** [comment]
@yuvipanda @GeorgianaElena that's it posted. Please drop me a line if you have any feedback, thanks!

**Comment by yuvipanda** [comment]
image

This is great! Thanks :)

**Comment by GeorgianaElena** [comment]
This has now been deployed to both staging and prod :tada: Merging it now.

**Pull request merged**
